### PR TITLE
restore windows builds

### LINKED ISSUE #6: Restore windows when gradle is available
## Notes
Once a compatible gradle is available, we should restore windows builds.

## References
- skip added in #4
- blocked by https://github.com/conda-forge/gradle-feedstock/pull/51

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- fixes #6

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by abloemert** [comment]
Hi @bollwyvl, what is the status of this PR? Do we only have to @conda-forge-admin please rerender or do we need to do more?

**Comment by abloemert** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
the build chain was breaking last i checked. i think someone with a need for this, the windows machine to debug on, and preferably java experience, would need start a new PR based on this.

**Comment by bollwyvl** [comment]
Fixed by #23

**Pull request closed without merging**
